module FS.GG.Governance.VerifyJson.Tests.GoldenTests

open System
open System.IO
open Expecto
open FS.GG.Governance.VerifyJson
open FS.GG.Governance.VerifyJson.Tests.Support

// T027 (US3) — `ofVerifyDecision` over a fixed fixture equals a committed golden baseline (SC-004). The
// baseline is regenerated by running this test once with BLESS_GOLDEN=1; thereafter any drift fails the test.

let private goldenPath =
    Path.Combine(repoRoot, "tests", "FS.GG.Governance.VerifyJson.Tests", "verify.golden.json")

let private fixtureDoc () =
    VerifyJson.ofVerifyDecision richDecision (Some mixedReport) mixedOutcomes

[<Tests>]
let tests =
    testList
        "VerifyJson golden (US3)"
        [ test "the fixed fixture projection equals the committed golden baseline" {
              let actual = fixtureDoc ()

              if Environment.GetEnvironmentVariable "BLESS_GOLDEN" = "1" then
                  File.WriteAllText(goldenPath, actual)

              let golden = File.ReadAllText goldenPath
              Expect.equal actual golden "verify.json golden drifted — regenerate with BLESS_GOLDEN=1 dotnet test"
          } ]
