module FS.GG.Governance.RefreshCommand.Tests.EndToEndTests

open Expecto
open FS.GG.Governance.FreshnessKey.Model
open FS.GG.Governance.RefreshJson.RefreshModel
open FS.GG.Governance.RefreshCommand
open FS.GG.Governance.RefreshCommand.Tests.Support

// The Principle-V end-to-end proof: `Interpreter.run` with REAL ports over a REAL temp repo, regenerating a
// REAL stale view through the REAL F051 process port (the deterministic `cp` generator). Currency is by
// digest, not file presence (SC-002): a re-run with no change regenerates nothing and exits 0.

let private statusOf (m: Loop.Model) (viewId: string) =
    m.Decision
    |> Option.bind (fun d -> d.Views |> List.tryFind (fun v -> v.Entry.ViewId = viewId))
    |> Option.map (fun v -> v.Status)

[<Tests>]
let tests =
    testList
        "EndToEnd"
        [ test "first run regenerates the view (exit 5); re-run is all-current (exit 0), by digest" {
              withTempRepo refreshYmlOneView (fun d -> writeFile d "src.txt" "hello\n") (fun repo ->
                  let m1 = runReal repo (requestFor repo)
                  Expect.equal m1.Exit ViewsRegenerated "first generation regenerates (exit 5)"
                  Expect.isTrue (fileExists repo "out.txt") "the view was written"
                  Expect.equal (readFile repo "out.txt") "hello\n" "regenerated bytes equal the generator output"
                  Expect.isTrue (fileExists repo ".fsgg/refresh.lock.json") "recorded provenance written"

                  let before = snapshotTree repo
                  let m2 = runReal repo (requestFor repo)
                  Expect.equal m2.Exit NothingToRefresh "re-run with no change ⇒ nothing to refresh (exit 0)"
                  Expect.equal (snapshotTree repo) before "re-run writes nothing")
          }

          test "mutating a source makes exactly that view stale; it regenerates with the drifted category" {
              withTempRepo refreshYmlOneView (fun d -> writeFile d "src.txt" "hello\n") (fun repo ->
                  runReal repo (requestFor repo) |> ignore // seed current
                  writeFile repo "src.txt" "changed\n"

                  let m = runReal repo (requestFor repo)
                  Expect.equal m.Exit ViewsRegenerated "the stale view regenerated (exit 5)"
                  Expect.equal (readFile repo "out.txt") "changed\n" "regenerated bytes equal the new source"

                  match statusOf m "doc" with
                  | Some(Regenerated drifted) -> Expect.equal drifted [ CoveredArtifactsCat ] "the source digest drifted"
                  | other -> failtestf "expected Regenerated, got %A" other)
          }

          test "multi-stale: each view regenerates; the others are byte-for-byte untouched" {
              let writeSources d =
                  writeFile d "a.txt" "alpha\n"
                  writeFile d "b.txt" "beta\n"

              withTempRepo refreshYmlTwoViews writeSources (fun repo ->
                  // Seed current, then mutate ONLY a.txt.
                  runReal repo (requestFor repo) |> ignore
                  let bOut = readFile repo "b.out"
                  writeFile repo "a.txt" "ALPHA\n"

                  let m = runReal repo (requestFor repo)
                  Expect.equal m.Exit ViewsRegenerated "exit 5"
                  Expect.equal (readFile repo "a.out") "ALPHA\n" "the stale view regenerated"
                  Expect.equal (readFile repo "b.out") bOut "the current view is untouched"

                  match statusOf m "cat" with
                  | Some Current -> ()
                  | other -> failtestf "expected the untouched view Current, got %A" other)
          }

          test "an empty manifest is nothing-to-refresh (exit 0), FR-012" {
              withTempRepo refreshYmlEmpty (fun _ -> ()) (fun repo ->
                  let m = runReal repo (requestFor repo)
                  Expect.equal m.Exit NothingToRefresh "empty manifest ⇒ exit 0"
                  Expect.isFalse (fileExists repo ".fsgg/refresh.lock.json") "nothing written")
          } ]
