module FS.GG.Governance.RefreshCommand.Tests.Support

open System
open System.IO
open System.Security.Cryptography
open FS.GG.Governance.FreshnessKey.Model
open FS.GG.Governance.RefreshJson.RefreshModel
open FS.GG.Governance.RefreshCommand

// Shared REAL-input builders for the F057 RefreshCommand tests (Principle V — every value below is a real,
// literally-constructible typed value or a real on-disk temp fixture, never a mock). The edge tests read a
// REAL temp-repo fixture (`.fsgg/refresh.yml` + the declared source files) through `Interpreter.run` over the
// REAL F029/F051/RefreshJson cores with a REAL deterministic generator command (`cp`); the pure-core tests
// consume hand-built typed values. No network, no registry (SC-007).

// ── temp-repo fixture helpers (the ReleaseCommand/VerifyCommand precedent) ──

let withTempDir (body: string -> 'a) : 'a =
    let dir = Path.Combine(Path.GetTempPath(), "fsgg-refresh-" + Guid.NewGuid().ToString("N"))
    Directory.CreateDirectory dir |> ignore

    try
        body dir
    finally
        try
            Directory.Delete(dir, true)
        with _ ->
            ()

let writeFile (dir: string) (relPath: string) (content: string) : unit =
    let full = Path.Combine(dir, relPath)

    match Path.GetDirectoryName full with
    | null -> ()
    | parent -> Directory.CreateDirectory parent |> ignore

    File.WriteAllText(full, content)

let readFile (dir: string) (relPath: string) : string = File.ReadAllText(Path.Combine(dir, relPath))

let fileExists (dir: string) (relPath: string) : bool = File.Exists(Path.Combine(dir, relPath))

let sha256Hex (s: string) : string =
    use sha = SHA256.Create()
    sha.ComputeHash(Text.Encoding.UTF8.GetBytes s) |> Array.map (fun b -> b.ToString("x2")) |> String.concat ""

/// A content-hash snapshot of every file under `dir` (relative path -> sha). The no-mutation guard compares
/// two snapshots for byte-for-byte equality.
let snapshotTree (dir: string) : Map<string, string> =
    Directory.GetFiles(dir, "*", SearchOption.AllDirectories)
    |> Array.map (fun f -> Path.GetRelativePath(dir, f).Replace('\\', '/'), sha256Hex (File.ReadAllText f))
    |> Map.ofArray

// ── refresh.yml fixtures (row-local surface; kebab-case kind tokens; `cp` as a deterministic generator) ──

/// One view "doc" (kind baseline): source `src.txt`, output `out.txt`, regenerated by `cp src.txt out.txt`.
let refreshYmlOneView =
    "views:\n"
    + "  - id: doc\n"
    + "    kind: baseline\n"
    + "    output: out.txt\n"
    + "    sources:\n      - src.txt\n"
    + "    generator: [\"cp\", \"src.txt\", \"out.txt\"]\n"
    + "    generatorBasis: g1\n"

/// Two independent views (`doc` from `a.txt`->`a.out`, `cat` from `b.txt`->`b.out`).
let refreshYmlTwoViews =
    "views:\n"
    + "  - id: doc\n"
    + "    kind: baseline\n"
    + "    output: a.out\n"
    + "    sources:\n      - a.txt\n"
    + "    generator: [\"cp\", \"a.txt\", \"a.out\"]\n"
    + "    generatorBasis: g1\n"
    + "  - id: cat\n"
    + "    kind: rule-catalog\n"
    + "    output: b.out\n"
    + "    sources:\n      - b.txt\n"
    + "    generator: [\"cp\", \"b.txt\", \"b.out\"]\n"
    + "    generatorBasis: g1\n"

/// An empty manifest (valid — "nothing to refresh", FR-012).
let refreshYmlEmpty = "views: []\n"

/// A view whose declared source does NOT exist (⇒ stale-unresolved).
let refreshYmlMissingSource =
    "views:\n"
    + "  - id: doc\n"
    + "    kind: baseline\n"
    + "    output: out.txt\n"
    + "    sources:\n      - absent.txt\n"
    + "    generator: [\"cp\", \"absent.txt\", \"out.txt\"]\n"
    + "    generatorBasis: g1\n"

let ymlLines (yml: string) : string list =
    yml.Replace("\r\n", "\n").Split('\n') |> List.ofArray

let parseYml (yml: string) : GenerationManifest =
    match Declaration.parse (ymlLines yml) with
    | Ok m -> m
    | Error e -> failwithf "fixture refresh.yml failed to parse: %s" e.Reason

/// Materialize a temp repo with `<repo>/.fsgg/refresh.yml` = `yml` and the declared sources via
/// `writeSources`, run `body repoDir`, then clean up.
let withTempRepo (yml: string) (writeSources: string -> unit) (body: string -> 'a) : 'a =
    withTempDir (fun dir ->
        writeFile dir (Path.Combine(".fsgg", "refresh.yml")) yml
        writeSources dir
        body dir)

// ── default request + ports ──

let requestFor (repo: string) : Loop.RunRequest =
    { Repo = repo
      DryRun = false
      Scope = Loop.AllViews
      Format = Loop.Text
      RefreshOut = None }

/// Run the command end to end through the REAL ports against a real temp repo.
let runReal (repo: string) (request: Loop.RunRequest) : Loop.Model =
    Interpreter.run (Interpreter.realPorts repo) request

// ── hand-built FreshnessKey-input values for the pure currency/loop tests (no disk) ──

let digestsOf (xs: string list) : ArtifactHash list = xs |> List.map ArtifactHash
// 074: findRepoRoot consolidated into the shared RepositoryHelpers (sln||slnx superset).
let repoRoot = FS.GG.Governance.Tests.Common.RepositoryHelpers.repoRoot
